source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DLinkSDK/deeplink-dev-specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FingerPrintDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FingerPrintDemo
  pod 'FingerprintKit'

  target 'FingerPrintDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FingerPrintDemoUITests' do
    # Pods for testing
  end

end
